### ISSUE TITLE
Using different protocols causes already running instances to crash

### ISSUE THREAD

**Issue by deividasjackus** [ice-services/moleculer#103]
I had one broker running using the old protocol and a second broker using the updated protocol trying to connect to the same transporter. The second instance threw an error saying there's a protocol mismatch as expected. However unexpectedly this also caused the old instance to crash:

![image](https://user-images.githubusercontent.com/8995502/30686515-c937c788-9eb8-11e7-940d-77bb0a2d6b3a.png)

**Comment by icebob** [comment]
Same as #90

**Comment by deividasjackus** [comment]
You are right, apologies; closing this one.
