### ISSUE TITLE
NATS Streaming transporter

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#104]
https://github.com/nats-io/node-nats-streaming

**Comment by icebob** [comment]
https://github.com/ice-services/moleculer/tree/nats-streaming

**Comment by icebob** [comment]
https://github.com/ice-services/moleculer/tree/nats-streaming

**Comment by icebob** [comment]
Dropped

**Comment by icebob** [comment]
https://dev.to/byronruth/use-cases-for-persistent-logs-with-nats-streaming

**Comment by TomKaltz** [comment]
Why dropped?

**Comment by icebob** [comment]
When I tried to implement it, I couldn't figure out how to set which topic will be stored, so the server stores all messages including internal messages (DISCOVER, HEARTBEAT...etc) But for event sourcing, we need to store the EVENT messages only.

Otherwise, the branch exists, so somebody can continue it.

**Comment by TomKaltz** [comment]
Might need to use both regular NATS and NATS Streaming separately for
different use-cases.  Would this be a good design to support both via
option in Broker?

**Comment by zllovesuki** [comment]
It's possible to have an `eventSourcing` option alongside with `transporter`. In that case, `eventSourcing` only accepts NATS Streaming or Kafka (and maybe optionally rejects those on `transporter`). I will take a look at that branch once I'm less busy...
