### ISSUE TITLE
Add Rate Limit to service layer

### ISSUE THREAD

**Issue by go4cas** [ice-services/moleculer#116]
Allow for each service to have its own Rate Limit setting (similar to the rate limiter in [moleculer-web](https://github.com/ice-services/moleculer-web/pull/17).

**Comment by go4cas** [comment]
Moved to moleculer-web repo: [#18](https://github.com/ice-services/moleculer-web/issues/18).

**Comment by TomKaltz** [comment]
Why was this moved to moleculer-web?  This should be a core service level feature.

**Comment by kokoraka** [comment]
> Why was this moved to moleculer-web? This should be a core service level feature.

Agree with this, are there any plan to add rate limit to service level @icebob ?

**Comment by budiselic** [comment]
Any update on this? This really should be also a core service level feature.

**Comment by intech** [comment]
@budiselic The original problem was related to moleculer-web, and there is a [solution](https://github.com/moleculerjs/moleculer-web/pull/271).
Do you want to be able to limit the level of microservices? Then perhaps you should look at the capabilities of the transport and the use of its load balancer.
