### ISSUE TITLE
Fix typos in documentation

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#118]
My native language is not English. Would be good if someone can help me to fix typos in documentation. Thank you!

**Comment by BeaData** [comment]
Hi there, I would be happy to help with that :)

**Comment by icebob** [comment]
Great! There are docs files in this [repo](https://github.com/ice-services/site/tree/master/source/docs).

**Comment by jonathan-kosgei** [comment]
Hi, I'd like to help too :) Checking out the link you posted

**Comment by icebob** [comment]
I need someone who do it really :confused:

**Comment by GPlay97** [comment]
@icebob I've already created some improvement. I can check the other docs file as well if you like, but I need some reaction/response. Would be great if you can accept my first PR I made for the doc file.

**Comment by icebob** [comment]
@GPlay97 your fixes in the PR is good, but I'm waiting for new ones, because you don't need to create new PRs for every sentences :) All fixes in one PR.
Thank you!

**Comment by GPlay97** [comment]
@icebob Okay, thank you. Sorry, I was unsure, since this was my very first public PR. 

I will enhance it as soon as possible and merge them all together. Thank you :)

**Comment by icebob** [comment]
[Done](https://github.com/ice-services/site/pull/4) by @GPlay97.
