### ISSUE TITLE
Registry does not respect configured strategy

### ISSUE THREAD

**Issue by Birkenstab** [ice-services/moleculer#121]
As I found out the registry class always uses RoundRobinStrategy for ActionCatalog and EventCatalog and my tests showed that the config option `registry: {strategy: Moleculer.Strategies.Random}` has no effect. 
ActionCatalog and EventCatalog are always initialized with RoundRobinStrategy: https://github.com/ice-services/moleculer/blob/master/src/registry/registry.js#L42-L43
And is the correct config name 'strategy' (see [service-broker.js:51](https://github.com/ice-services/moleculer/blob/master/src/service-broker.js#L51)) or 'StrategyFactory' (see [registry.js:38](https://github.com/ice-services/moleculer/blob/master/src/registry/registry.js#L38))?

**Comment by icebob** [comment]
Sorry, I will check it.

**Comment by Birkenstab** [comment]
Thanks

**Comment by icebob** [comment]
The correct name in broker options is `StrategyFactory`, I will fix it.

**Comment by sjmcdowall** [comment]
I rather like the name “strategy” better for an option than having to type out “StrategyFactory”  — which really doesn’t add much clarity IMHO.   So which will you fix?  :)

**Comment by icebob** [comment]
Yes, I'm thinking on same thing. The strategy is better in options, but StrategyFactory is better in Registry source code :)
So `strategy` stays, and I fix in the Registry code.

**Comment by sjmcdowall** [comment]
Sounds perfect!

**Comment by icebob** [comment]
Fixed. Tomorrow I will release it.

**Comment by Birkenstab** [comment]
That's great! Thank you!

**Comment by icebob** [comment]
Fix is released in v0.11.5
