### ISSUE TITLE
Action cacher key generator

### ISSUE THREAD

**Issue by Equals182** [ice-services/moleculer#125]
Hey
I did some research and it looks like Base Cacher's [key generator function](https://github.com/ice-services/moleculer/blob/master/src/cachers/base.js#L138) doesn't respect any of ctx.meta values which makes it useless when combined with molecular-web's proposed auth method which relies on ctx.meta as storage for logged in user.
I think the best option with backwards compatibility rn is to add an option (besides `ttl`) with custom keygen function. Function supposed to return cache key and accepts `ctx` and `action.cache.keys` as parameters. This custom function can replace or improve default function's result. 

Please correct me if I'm wrong
Thanks

**Comment by icebob** [comment]
Good idea.

**Comment by icebob** [comment]
I implement it in https://github.com/ice-services/moleculer/pull/126

**Comment by icebob** [comment]
Released in https://github.com/ice-services/moleculer/releases/tag/v0.11.6
