### ISSUE TITLE
Type 'object' return error for me. Could it use 'any' instead?  

### ISSUE THREAD

**Issue by dani8art** [ice-services/moleculer#130]
https://github.com/ice-services/moleculer/blob/6fa6f4699c053d7331025cba221dcc8a9a0e0663/index.d.ts#L48

**Comment by dani8art** [comment]
@rmccallum81, what do you think about?

**Comment by rmccallum81** [comment]
I think it should be `ActionParams` as that is what it is generated from

**Comment by icebob** [comment]
What is the error? Because ctx.params is initialized to `{}`
https://github.com/ice-services/moleculer/blob/6fa6f4699c053d7331025cba221dcc8a9a0e0663/src/context.js#L58
https://github.com/ice-services/moleculer/blob/6fa6f4699c053d7331025cba221dcc8a9a0e0663/src/context.js#L159

**Comment by rmccallum81** [comment]
Sorry I spoke too soon, it isn't `ActionParams` it could be `{[name: string]: any}` but `object` should be fine.

**Comment by dani8art** [comment]
Whit `object` I recive this error:
```
return Promise.resolve(`welcome ${ctx.params.name}`);
src/test/services/greeter.service.ts(25,50): error TS2339: Property 'name' does not exist on type 'object'.
```

**Comment by dani8art** [comment]
With `{[name: string]: any}` It works fine for me. Do you think we should change all `object` by `{[name: string]: any}`?  `object` seems to work wrong and to be more restrictive than `{[name: string]: any}`

**Comment by icebob** [comment]
I can't decide it, because I don't know Typescript. So it's your choice :)

**Comment by rmccallum81** [comment]
It would work but I'd say define a type with that definition instead of adding the full def everywhere.

**Comment by rmccallum81** [comment]
Also with object you can access custom properties using `objectVar["prop"]`

**Comment by dani8art** [comment]
Yes, it's true, but I think dot notation is clearer, isn't it? 
Who will do it? do you want to do it?

**Comment by rmccallum81** [comment]
I can put it in today
