### ISSUE TITLE
async await

### ISSUE THREAD

**Issue by wmhafiz** [ice-services/moleculer#136]
hey,
this is more a question than an issue.

is it a good idea to setup babel in my moleculer project to enable use of 

- async await
- import / export statements
- etc

is it possible to pass babel flag to moleculer-runner? 

btw this is a really great library, thanks for open sourcing it!

**Comment by icebob** [comment]
Hi,

I have not tried Moleculer-Runner with Babel.

**Comment by wmhafiz** [comment]
i see. what about async await? those are already supported in node right?

basically i wanted to convert from

``` javascript
const run = () => {
  broker.start()
    .then(() => broker.waitForServices('some-service'))
    .then(() => broker.call('some-service.test', { some: 'payload' }))
    .then((result) => {
    // do something with the result
    })
    .then(() => console.log('done'));
};

run();
```

to 

``` javascript
const run = async () => {
  await broker.start();
  await broker.waitForServices('some-service');
  const result = await broker.call('some-service.test', { some: 'payload' });
  // do something with the result
};

run();
```
it seems to be working when i tried it out but is there any caveats on coding this way?

also, instead of having to wrap `broker.start()` with a custom async function, maybe we can have an onReady API like so:

``` javascript
broker.ready(async () => {
  await broker.start();
  await broker.waitForServices('some-service');
  const result = await broker.call('some-service.test', { some: 'payload' });
  // do something with the result
})
```

**Comment by Nathan-Schwartz** [comment]
@wmhafiz We use async/await with Moleculer in production and haven't had any issues with it.

Using promise chains off of `broker.start` or writing something similar to your `run` function has been a good solution for us so far.

I don't think I understand the purpose of `broker.ready`. If the same function needs to be written either way, it doesn't seem to provide very much utility.

**Comment by wmhafiz** [comment]
noted, thanks for the answers!
