### ISSUE TITLE
Running several brokers on the same node

### ISSUE THREAD

**Issue by mast** [ice-services/moleculer#140]
First of all let me thank you guys for such incredible framework!
I found it yesterday and immediately fell in love into it.

I'm now playing with moleculer a bit and currently I'm testing interconnectivity.
And it appeared that I'm a little bit confused with behaviour I observe, so I decided to ask you if this is intended behaviour.

I have 2 physical hosts and trying to interconnect my microservices. I'm using NATS and I have 2 folders created by molecular-cli (nano template).
First microservice has action test1.hello and second one has test2.hello implemented.
I'm starting my services with moleculer-runner.

When I start test1 on host1 and test2 on host2, everything works as expected. I run in repl mode and on both hosts I can see both services and both actions and I can run them.

| Broker  | Visible nodes  | Visible services  | Visible actions  |
|---|---|---|---|
| test1 on host 1  | host1, host2  | test1, test2  | test1.hello, test2.hello  |
| test2 on host 2  | host1, host2  | test1, test2  | test1.hello, test2.hello  |

Then I try to start another instance of test2 on host1, so I'd have (test1 and test2) on host1 and (test2) on host2. As soon as I do that, I see following picture.

| Broker  | Visible nodes  | Visible services  | Visible actions  |
|---|---|---|---|
| test1 on host 1  | host1, host2  | test1, test2  | test1.hello, test2.hello  |
| test2 on host 2  | host1, host2  | test2  | test2.hello  |
| test2 on host 1  | host1, host2  | test2  | test2.hello  |

So two brokers on both hosts lose service test1.
It doesn't seems like good for me.

Also I noticed that all my brokers have nodeID set to null (so it should match hostname). But when I put some custom nodeID into third starting broker, I'm getting situation fixed. Both actions become visible on all three brokers, but through 3 nodes in this case.

Could you please advice if this is bug or misconfiguration?
Also do you have any documentation about Service Registry? I see it's marked as "coming soon" now.

**Comment by mast** [comment]
Looking into source code it seems nodeID is considered as unique identity, i.e. it should not be 2 nodes with the same nodeID in the system. If so, it explains why (test1, host1) service was replaces by (test2, host1) service, since they share same nodeID.
I think I will just relate nodeID with pid in this case (may be it should be done by default to avoid confusion).

**Comment by icebob** [comment]
Yes, if you are running multiple brokers on the same node, you have to use different nodeIDs. The default nodeID is only coming from hostname, which is enough if you are running it in Docker environment.
If you want to run multiple brokers, use this nodeID definition in your `moleculer.config.js`:
```js
  nodeID: os.hostname() + "-" + process.pid
```

Btw, I'm glad that you like our framework. :+1: If you have more questions, join our [chat on gitter](https://gitter.im/ice-services/moleculer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by mast** [comment]
Thanks, @icebob . Fair enough!
