### ISSUE TITLE
Omitting infrastructure info when in production

### ISSUE THREAD

**Issue by ColonelBundy** [ice-services/moleculer#141]
Having stuff like https://github.com/ice-services/moleculer/blob/master/src/errors.js#L113 might not raise any security issues but, good practice would be to not divulge any infrastructure information to the end user. it's however super helpful in development.

#### Solution
Hide when ```process.env.NODE_ENV == 'production'``` or behind a flag.

**Comment by icebob** [comment]
Thanks. good idea.

**Comment by icebob** [comment]
I wanted to fix it, but if I skip nodeID from the error objects, it won't be visible in the logs (in production) too which is not a good idea. But currently, the nodeID will be visible in errors if you make only direct calls.

So at present the best solution if you handle errors in moleculer-web and omit the sensitive information.
