### ISSUE TITLE
Send 503 instead of 404 when service is registered in routes

### ISSUE THREAD

**Issue by ColonelBundy** [ice-services/moleculer#144]
I recently ran into a "bug" where I would call a service: ```example.com/api/hello``` and I would get a 404 since the service is not up yet, but the gateway has the routes registered for this particular service.

### Proposal:
Send a 503 if the service exists in the route whitelist/aliases

### Current hack to make this work (typescript)
```
import { Errors } from 'moleculer'
import _ = require('lodash');

onError(req, res, err) {
  switch (err.constructor) {
    case Errors.ServiceNotFoundError:
      err.message = 'Service not found';
      if (_.findIndex(this.routes[0].whitelist, i => i == err.data.action) != -1) {
        err.message = 'Service unavailable';
        err.code = 503;
      }
    break;
  }
}
```

**Comment by icebob** [comment]
Thanks, but please move it to `moleculer-web` [repo's issues](https://github.com/ice-services/moleculer-web/issues)

**Comment by ColonelBundy** [comment]
@icebob My bad! Thanks!
