### ISSUE TITLE
Call a service method on a different broker

### ISSUE THREAD

**Issue by 1N50MN14** [ice-services/moleculer#150]
`Inside the action you can call other actions in other services with ctx.call method. It is an alias to broker.call, just set itself as parent context (due to metrics).`

This is great because it allows for chaining of calls, however, I'm able to do that only as long as the service is loaded on the same node/broker, i.e. given `return ctx.call("service.method")` where `service` is on a separate broker, `service.method` will not be found. I am use gnats as transport.
 
Maybe I'm missing on something? thanks ;)

**Comment by 1N50MN14** [comment]
Upon closer inspection I see repl outputs `Waiting for service(s) 'myservice'..` - NATS client is connected on both service brokers.

**Comment by icebob** [comment]
No, you can call services on other nodes with `ctx.call` of course. This is the point, that you don't know a given service which nodes is running and how many instances.

**Comment by icebob** [comment]
Check the `nodes` command result in repl that all nodes see each others.

**Comment by 1N50MN14** [comment]
@icebob Thank you, yes I understood that, the problem I'm facing is that even though the nodes are connected (I see that in the logs, also for gnats) the service which I'm attempting to require another logs `Waiting for service(s) 'myservice'` - it basically waits for it but never finds it, as a result `ctx.call()` returns and 404 error message. I'm thinking could it be related to nodeId being `undefined`?

**Comment by 1N50MN14** [comment]
(PS awesome job on a well thought framework!)

**Comment by icebob** [comment]
I think the problem is that you was running multiple brokers with the same nodeID. (If nodeID is empty it will be the computer name). I recommend to use manual nodeID or something similar: `nodeID: "node-" + process.pid`

**Comment by 1N50MN14** [comment]
You I have *just* tested it, this was indeed the case! Thank you!

Very excited about moleculer!
