### ISSUE TITLE
How to config load balance strategy via environment?

### ISSUE THREAD

**Issue by zhaoyao91** [ice-services/moleculer#157]
How to config load balance strategy, better, via environment?

Looking through the docs, it seems relating to so-called `registry`， but there is not any doc about it.

**Comment by chux0519** [comment]
According to the source, it seems that currently only supports two strategies.

### [RandomStrategy](https://github.com/ice-services/moleculer/blob/master/src/strategies/random.js#L19)  

```
select(list) {
		return list[random(0, list.length - 1)];
	}
```

### [RoundRobinStrategy](https://github.com/ice-services/moleculer/blob/master/src/strategies/round-robin.js#L25)  

```
select(list) {
		// Reset counter
		if (this.counter >= list.length) {
			this.counter = 0;
		}
		return list[this.counter++];
	}
```

**Comment by zhaoyao91** [comment]
It seems that only round-robin and random strategies are supported by now, but there should be better strategies for distributed docker cluster environment, such as prefer-most-resources.

**Comment by icebob** [comment]
Yes currently there are only 2 strategies. But you can create your custom strategy easily. Check the `RandomStrategy` source: https://github.com/ice-services/moleculer/blob/master/src/strategies/random.js
The `list` contains [`Endpoint`s](https://github.com/ice-services/moleculer/blob/master/src/registry/endpoint.js)

**Comment by chux0519** [comment]
But still, it seems can not be controlled by the environment variables, because the value of the `REGISTRY_STRATEGY` field is a class

**Comment by icebob** [comment]
It's true. Workaround: `strategy: process.env.REGISTRY_STRATEGY == "random" ? Moleculer.Strategies.Random : Moleculer.Strategies.RoundRobin`
