### ISSUE TITLE
Built-in clustering option in Moleculer Runner

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#167]
```sh
$ moleculer-runner --hot --instances 4
```

Same solution: https://github.com/ice-services/moleculer/blob/master/examples/loadtest/clients.js

@tinchoz49

**Comment by tinchoz49** [comment]
I will try to do a PR today :)

**Comment by tinchoz49** [comment]
@icebob today we talk about a way to run workers with different nodeID. Well, in my project I have a lot of moleculer nodes in different docker containers and I generate a nodeID for each node using node-uuid.

What I think is that maybe we can define a way to generate a nodeID when we use `--instances` flag.

For example, in one of the docker container runs `moleculer-runner --instances 4 services` and it gives you a nodeID:

df7cca36-3d7a-40f4-8f06-ae03cc22f045-1
df7cca36-3d7a-40f4-8f06-ae03cc22f045-2
df7cca36-3d7a-40f4-8f06-ae03cc22f045-3
df7cca36-3d7a-40f4-8f06-ae03cc22f045-4

where the nodeID is a `uuidv4` that represents something like the NODE_UNIQUE_ID + `worker.id` instance.

**Comment by icebob** [comment]
I don't think it is a good approach because I want to keep the opportunity that the developer can define it.
My idea is that we use the nodeID from `config` and add the `worker.id` as a suffix like you did `xxxxx-1`. 

### Cases:
**User defined nodeID:**
```js
module.exports = {
  nodeID: "my-node"
}
```
Instance IDs:
```
my-node-1
my-node-2
my-node-3
my-node-4
```

**Your uuid approach**:
```js
module.exports = {
  nodeID: uuid.v4()
}
```
Instance IDs:
```
df7cca36-3d7a-40f4-8f06-ae03cc22f045-1
df7cca36-3d7a-40f4-8f06-ae03cc22f045-2
df7cca36-3d7a-40f4-8f06-ae03cc22f045-3
df7cca36-3d7a-40f4-8f06-ae03cc22f045-4
```

**Not defined ID**
In this case we use the [default broker logic](https://github.com/ice-services/moleculer/blob/master/src/utils.js#L35), get the computer name as nodeID.
```js
module.exports = {
  nodeID: null
}
```
Instance IDs:
```
my-computer-1
my-computer-2
my-computer-3
my-computer-4
```

**Comment by sjmcdowall** [comment]
Perhaps as a “compromise” — if the nodeID is defined use that and suffix it with the worker.id <http://worker.id/> .. However, if there is no nodeID defined already, default to creating one via the uuid method (and append the worker.id <http://worker.id/>).  

However, I do have an “edge” case question:  If the number of instances for the worker is only 1 (the default) should the worker.id <http://worker.id/> be placed on the instance IDs or should the instance IDs and node IDs be the same in that edge case? 

I THINK there is a case to be made for always suffixing a worker.id <http://worker.id/> to the nodeID to create the instance IDs so it’s consistent.. <shrug>

**Comment by icebob** [comment]
Released
