### ISSUE TITLE
Survey: Moleculer Usage 2018

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#170]
Hi guys,
I need your help! I made a Moleculer usage survey. If you have time, please [take the survey](https://docs.google.com/forms/d/e/1FAIpQLScLuBFJRFhgkd-X0tfCCbxaZv2VPm4rwCDIdbhT0mBYTit_dg/viewform?usp=sf_link). It only takes 2 minutes, but your feedback will help me making Moleculer better in the future.

:sparkles: [Take the survey](https://docs.google.com/forms/d/e/1FAIpQLScLuBFJRFhgkd-X0tfCCbxaZv2VPm4rwCDIdbhT0mBYTit_dg/viewform?usp=sf_link) :sparkles: 

Thank you in advance!

**Comment by tinchoz49** [comment]
minor typo @icebob in the logger question. Pino instead of Pivo. Can I share this Survey in twitter?

**Comment by icebob** [comment]
Thank you. I fixed. Of course, share it where you like :) Thanks.

**Comment by icebob** [comment]
The survey is closed. Result: https://medium.com/moleculer/moleculer-usages-survey-results-441fed3264d
