### ISSUE TITLE
Incomplete protocol description? 

### ISSUE THREAD

**Issue by ToGoBananas** [ice-services/moleculer#173]
Hello
I am trying to implement protocol in python (https://moleculer.services/api-0.11/protocol.html)
But, when I am running moleculer service using simple command:
`moleculer connect amqp://localhost:5672`
it creates queue `MOL.HEARTBEAT.<nodeID>`, but there is no mention about this in protocol description
So, whether description complete? and can I implement this protocol for python services?

**Comment by icebob** [comment]
Hi,
First of all, I'm glad that you start implementing Moleculer protocol in Python. It's great!

The protocol documentation is up-to-date and complete, but AMQP implementation is a bit different. You can find some comment about queues & exchanges in the code by @Nathan-Schwartz: https://github.com/ice-services/moleculer/blob/master/src/transporters/amqp.js#L288

**Comment by ToGoBananas** [comment]
Here very rude implementation of protocol (JSON serializer, AMQP transport) for my own needs, but maybe someone can find this helpful
https://github.com/ToGoBananas/moleculer-python
