### ISSUE TITLE
How to create an adapter for another database?

### ISSUE THREAD

**Issue by ArnoBuschmann** [ice-services/moleculer#181]
If someone wants to use a database other than Mongo or Mysql, how would we create an approriate adapter for it?

Let's say, I'd like to use Arangodb https://www.arangodb.com/ in conjunction with Moleculer, how would that work?

**Comment by icebob** [comment]
Copy the mongo adapter source, and implement all class methods to use ArangoDB
https://github.com/ice-services/moleculer-db/blob/master/packages/moleculer-db-adapter-mongo/src/index.js
