### ISSUE TITLE
service schema gets before merging middleware which results in schema errors

### ISSUE THREAD

**Issue by mailaneel** [ice-services/moleculer#187]
I am using moleculer-db with mongoose and added this as a mixin.

```js
module.exports = {
  name: 'tenant',
  mixins: [mongooseDBMixin()],
  settings: {
    idField: 'id',
    fields: ['id', 'name', 'createdAt', 'updatedAt'],
  },
  actions: {
    create: {
      params: {}
    }
  },
  model: Tenant
}
```

results in below error

```
/app/node_modules/moleculer/src/service.js:228
throw new ServiceSchemaError(`Missing action handler on '${name}' action in '${this.name}' service!`);
ServiceSchemaError: Missing action handler on 'create' action in 'tenant' service!
at Service._createAction (/app/node_modules/moleculer/src/service.js:228:10)
```
but `create` handler is added by mongoose mixin

**Comment by icebob** [comment]
The `actions` is not mixed deeply. If you overwrite `create` action, it won't merge it with Mongoose mixin, so you have to create the `handler` too.

**Comment by mailaneel** [comment]
in this case how do i call parent hander
should i call it via adapter? ->this means we have to implement same logic implemented in create handler

any suggestions?

**Comment by icebob** [comment]
#188
