### ISSUE TITLE
Cant use with bluebird!

### ISSUE THREAD

**Issue by wi-ski** [ice-services/moleculer#202]
Getting:
```
UnhandledPromiseRejectionWarning: Error: cannot enable cancellation after promises are in use
```

If I require bluebird anywhere else in my project, I get this error due to:
https://github.com/ice-services/moleculer-web/blob/master/src/index.js#L83

This might actually be better placed in that repo :thinking:

**Comment by icebob** [comment]
Thanks, please move it to moleculer-web repo issues.

**Comment by icebob** [comment]
Is it with v0.12 right?
