### ISSUE TITLE
Who uses it? Usage examples

### ISSUE THREAD

**Issue by autoferrit** [ice-services/moleculer#40]
I was just discovering this project starting out on a new one of my own. It looks nice. but I was wondering where it has been used in production. Or if anyone notable was using it. I think it looks great but if im going to start something new I don't want to start with any random framework. 

as a comparison, outside of this i was probably going to go with hapi.js

**Comment by icebob** [comment]
Hi @autoferrit,
Moleculer is a very new microservices framework. It is under heavy development. And before v1.x.x it is not recommended for production. I'm working on it alone in all my free time (but it is limited). If you need immediately a stable microservices framework I don't recommend Moleculer.

**Comment by gino8080** [comment]
@icebob nice framework!

what you'll recommended for production?

**Comment by icebob** [comment]
Hi @gino8080,
there are many companies who using Moleculer in production. It means Moleculer is stable for production, but before version 1.x some main parts maybe will be changed in the future. So it is recommended to lock the version number in your project.

**Comment by gino8080** [comment]
@icebob thank you!
I would like to integrate it on a HAPI server

do you have any hints?

thank you very much!

**Comment by icebob** [comment]
I recommend checking the [moleculer-web](https://github.com/moleculerjs/moleculer-web) code how it integrates itself to Express as a middleware.

**Comment by tinchoz49** [comment]
Hi @gino8080 how are you?

We are using moleculer in production with hapi. What we did was create a hapi plugin that creates a service broker to connect our hapi server to the rest of the moleculer services that we have.
