### ISSUE TITLE
expose event or some trigger on disconnected!

### ISSUE THREAD

**Issue by svensklave** [ice-services/moleculer#41]
Would be nice to be able to listen on node for disconnected event
(when we are using 'moleculer-web')
so we can do some custom logic in that case
and also some parameter in settings so when some node goes down then show this kind of respnses
instead of hanging request to specific action (this happens after we stop/kill some node)
would be nice also to check if node is down or not 
before we call action

```
{
  "name": "ServiceNotFoundError",
  "message": "Service 'extra.hello' is not available!",
  "code": 501,
  "type": null,
  "data": {
    "action": "extra.hello"
  }
}
```
or
```
{
  "name": "NodeNotFoundError",
  "message": "Service 'extra.hello' on node 'server-1' is not available!",
  "code": 501,
  "type": null,
  "data": {
    "action": "extra.hello"
  }
}

```

yes we can use timeout but then it does not gives us a correct understanding what was happened
in case some node is disconnected
[TRANSIT] Node 'server-1' disconnected!

**Comment by icebob** [comment]
You can listen node disconnected right now. The `node.disconnected` or `node.broker` event is triggered (`broken` if not received heartbeat from node)

```js
broker.createService(ApiGwService, {
	settings: {...},

	events: {
		"node.disconnected"(node) {
			this.logger.warn(`The ${node.id} node is disconnected!`);
		},
		"node.broken"(node) {
			this.logger.warn(`The ${node.id} node is broken!`);
		}
	},
})
```

> In the next version I think I will merge these event to one.
