### ISSUE TITLE
CLI and REPL hangs when running Node 8.1

### ISSUE THREAD

**Issue by demetriusnunes** [ice-services/moleculer#43]
The generator always hangs on the "run npm install" question.

The `moleculer start` always hangs after `help` command.

I'm using node 8.1. Maybe that's it?

**Comment by demetriusnunes** [comment]
Just tested with 7.1 and it worked. So that's it.

**Comment by icebob** [comment]
I need help from somebody because I have no Mac.

**Comment by demetriusnunes** [comment]
I think the problem is actually node 8.1 and not OS X. Were you able to test it with Node 8.1?

**Comment by icebob** [comment]
Not yet, but I will try it.
The `moleculer start` starts the REPL mode which is a [vorpal](https://github.com/dthree/vorpal) module.

**Comment by icebob** [comment]
I tested  `moleculer start` on Node 8.1.1 on Win7 and it is working properly.

**Comment by icebob** [comment]
Reopen if the problem appears.
