### ISSUE TITLE
Move REPL to a separated optional module `moleculer-repl`

### ISSUE THREAD

**Issue by ecwyne** [ice-services/moleculer#44]
This package looks awesome! Great work so far, excited to see what else will come of it!

One thing I noticed is that a large chunk (~2/3) of the dependencies are only used for the REPL (vorpal, table, clui)
(collected using [cost-of-modules](https://github.com/siddharthkp/cost-of-modules))

<img width="333" alt="screen shot 2017-06-12 at 4 31 32 pm" src="https://user-images.githubusercontent.com/5205440/27059723-ef6322b6-4f8c-11e7-991b-f6a686769d85.png">

I haven't looked deeply enough into the source code to see if it would be possible. But I think it may be worth exploring making `moleculer-repl` a separate package that developers can add as a `devDepenency` and reduce final size of the production build.

**Comment by ecwyne** [comment]
It looks like it may be almost trivial to break the repl into another module. It's already just a function that expects a `ServiceBroker` instance.

```javascript
import {ServiceBroker} from 'molecule'r;
import startRepl from 'moleculer-repl';

const broker = new ServiceBroker();
// ... create services
repl(broker);
```

The only potential issue I see is that repl also uses `constants.js` and `health.js` both of which are used elsewhere in the codebase.

**Comment by icebob** [comment]
@ecwyne Thanks, it is a good idea! I will create a new repo for repl.

**Comment by icebob** [comment]
More info:
The `.health` is not problem because it's callable via `broker.getNodeHealthInfo`
The constants from `./constants` is exposed from package. E.g. `Moleculer.CIRCUIT_CLOSE`

**Comment by icebob** [comment]
I created [moleculer-repl](https://github.com/ice-services/moleculer-repl) and removed from `moleculer`. Tomorrows I will try it and if it's working properly in the next version will be released.

**Comment by icebob** [comment]
Released with v0.7.8.

The command is not changed. `broker.repl()` but need to install `npm install moleculer-repl` in the project.

**Comment by icebob** [comment]
Result:
![image](https://user-images.githubusercontent.com/306521/27180233-b5f4f91c-51d2-11e7-83f6-559d03373a5a.png)

**Comment by ecwyne** [comment]
Very cool! [This](https://github.com/ice-services/moleculer/blob/62850f87bf8f6834c86ab87eb4164488c5bbc215/src/service-broker.js#L234-L245) is a very elegant solution.

And the dependencies are 41% of what they used to be :+1:
