### ISSUE TITLE
Remove annoying favicon.ico error message when calling service from browser

### ISSUE THREAD

**Issue by demetriusnunes** [ice-services/moleculer#47]
When I call a service from Chrome, I always get:
`ServiceNotFoundError: Service 'favicon.ico' is not available!` followed by an error stack.

**Comment by icebob** [comment]
Yes, because Chrome is automatically try to download favicon for the given URL.

**Comment by Akhila-C-R** [comment]
Hi, I too get this issue, and I have not linked favicon anywhere on the project. How do I get rid of it? It's very annoying X(

**Comment by icebob** [comment]
Put a favicon.ico beside index.html

**Comment by Akhila-C-R** [comment]
> Put a favicon.ico beside index.html

But I don't need a favicon. And hence I have not linked it anywhere.

**Comment by sudeeep885** [comment]
You can remove the favicon request by adding the following line in your `<head>` section of your HTML page -

`<link rel="icon" href="data:,">`

**Comment by GOPIKAPANDI** [comment]
I am also getting the same error while running js file how to overcome it...what should I include in my json?
