### ISSUE TITLE
Which transporter should I use?

### ISSUE THREAD

**Issue by zhaoyao91** [ice-services/moleculer#52]
Is there any guideline to help choose transporter?

**Comment by icebob** [comment]
What you like :) I recommend the [NATS](http://nats.io)

**Comment by zhaoyao91** [comment]
@icebob Thanks. May I know the reason of recommendation for NATS? is it faster or stabler than redis or others? Or it has some what killer features?

On the other hand, why there isn't any decentralized transporter like tcp or mesh in seneca, which don't require another infrastructure to kick off the cluster?

**Comment by deividasjackus** [comment]
@zhaoyao91 this is a very opinionated question that's out of Moleculer's scope. You should make the choice between NATS/Redis/MQTT/others based on your own needs. Good rule of thumb is to use whatever you're most comfortable with.

In regards to your second question: https://github.com/ice-services/moleculer/issues/46

**Comment by icebob** [comment]
@zhaoyao91 Implement a message broker transporter is not too difficult because need to implement 4 methods, `connect` `close` `subscribe` and `publish`. But a tcp or udp based communication is more complicated. But maybe in the future somebody will create it for Moleculer :)
