### ISSUE TITLE
Where is moleculer's protocol? How to implement it in other language(go) ?

### ISSUE THREAD

**Issue by roytan883** [ice-services/moleculer#56]
NATS is beased on go language. I think it should be easy implement moleculer-go.
But i can't find the molecular's protocol.

**Comment by icebob** [comment]
I'm working on API documentation of Moleculer right now. I plan to add protocol docs as well.
Currently you can check the protocol from the [packets.js](https://github.com/ice-services/moleculer/blob/master/src/packets.js) and from [packets.proto](https://github.com/ice-services/moleculer/blob/master/src/serializers/proto/packets.proto)

**Comment by roytan883** [comment]
@icebob thanks

**Comment by icebob** [comment]
@roytan883 I created it: https://github.com/ice-services/moleculer/blob/master/docs/PROTOCOL.md

**Comment by icebob** [comment]
Published on site: http://moleculer.services/api-0.9/protocol.html
