### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#57]
We need a `namespace` property that we can segment our services. 
For example, we are running development & production services (or more production services) on the same transporter, but we need to avoid collisions.

Currently there is a `prefix` property in the Transporter options (which solve it), but I want to move it to ServiceBroker options (in v0.9.x).

```js
const broker = new ServiceBroker({
  logger: console,
  namespace: "blog" // for production
  namespace: "blog.dev" // for development
  namespace: "blog.test" // for testing
});
```
And it can be also set via environment variable `NAMESPACE`.

![image](https://user-images.githubusercontent.com/306521/29040717-620d2736-7bb0-11e7-8c3e-554b8dfdbe07.png)

**Comment by qdoop** [comment]
What about the POOL or SERVICE_POOL
Virtual you attach a broker to a Service Pool in order to provide and consume services.

**Comment by icebob** [comment]
Thank you for everybody who voted. It will be implemented in the next version as `namespace`.

**Comment by icebob** [comment]
Released: https://github.com/ice-services/moleculer/releases/tag/v0.9.0
