### ISSUE TITLE
If version is not a number, do not prefix with v

### ISSUE THREAD

**Issue by brad-decker** [ice-services/moleculer#58]
Would this be something that would align with the gameplan for Moleculer? Right now if version exists its being prefixed with a 'v' which makes sense for numerical versions. In our use case we might want to have different versions of a microservice running for various features we are working on. In that case i have suggested something like 'staging.serviceName.actionName'. Allowing individual teams to deploy microservices to our infrastructure that can be targeted via the api gateway for that specific environment/feature.

**Comment by icebob** [comment]
Thanks, I'm going to consider it.

**Comment by icebob** [comment]
I will implement it in the next release v0.9, because it is a breaking change.

**Comment by icebob** [comment]
Released: https://github.com/ice-services/moleculer/releases/tag/v0.9.0
