### ISSUE TITLE
Does it support event group?

### ISSUE THREAD

**Issue by zhaoyao91** [ice-services/moleculer#59]
If two services listen to a same event, when it occurs, both of them will receive the event, I guess.
Does moleculer support event group which is supported natively by nats and amqp?
Say, if the two services listen to a same event but and join a same group, only one of them will receive the event at a time.

**Comment by icebob** [comment]
Currently it is not available with events. 
Maybe you can cover it with `action` because it is load-balanced. Only one instance receives the action requests.

**Comment by zhaoyao91** [comment]
It's not good to use action since it can form only one group. Sometimes several groups are interested in some event. All groups will receive that event, but within that group, only one member will receive it.

**Comment by icebob** [comment]
Moleculer is not depends on transporter. So I can't implement NATS queueing because it won't able to work with other transporters.

**Comment by zhaoyao91** [comment]
For AMQP, it works since it has built-in queue which serves as group here naturally. For redis, I am not familiar with its pattern, but this feature may be made not mandatory so only available on some transporters.

**Comment by icebob** [comment]
Maybe relevant: #42
