### ISSUE TITLE
How to integrate it with Netflix Eureka?

### ISSUE THREAD

**Issue by danielsan** [ice-services/moleculer#65]
Hi everyone,

I'm trying to choose a microservices framework to use with node
but I really need to be able to integrate it with Eureka since we already have a
microservices infrastructure using Eureka :'(

Does anybody know how to use moleculer with Eureka for service register/discovery?

**Comment by icebob** [comment]
Hi,

sorry, but I don't know Eureka. I think you need to create an interface which can communicate each others.
