### ISSUE TITLE
Method/Action groups

### ISSUE THREAD

**Issue by deividasjackus** [ice-services/moleculer#69]
It'd be great to have better support for action/method grouping (`svc.actionGroup.subAction`).
Currently it's achievable using string literal keys:

```js
{
  name: "svc",

  methods: {
    "methodGroup.subMethod": () => 42,
  },

  actions: {
    "actionGroup.subAction"() {
      return this["methodGroup.subMethod"]();
    },
  },
}
```

Both the pattern and modularizing of service logic based on groups could be more elegant:

```js
{
  name: "svc",

  methods: {
    methodGroup: {
      subMethod: () => 42,
    },
  },

  actions: {
    actionGroup: {
      subAction() {
        return this.methodGroup.subMethod();
      },
    }
  },
}
```

**Comment by icebob** [comment]
I think the nested action can cause problem to detect it is an action or a group. Both are an `object`.
```js
actions: {
    find: {
        cache: true,
        params: {},
        handler(ctx) {}
    }
}

actions: {
    find: {
        all: {
            cache: true,
            params: {},
            handler(ctx) {}
        }
    }
}
```

**Comment by deividasjackus** [comment]
@icebob I thought so too, at first. But isn't an action always supposed to have a handler property that's guaranteed to be a function?

**Comment by icebob** [comment]
The broker sends the action definitions to other nodes without handler. So the remote nodes can't detect it.

**Comment by deividasjackus** [comment]
Couldn't the broker send an additional boolean property describing whether it's a group or not?

**Comment by tiaod** [comment]
What about 😄 
```
broker.createService({
    name: "math",
    actions: {
        'sub.action1':function(ctx){
          return 'hello'
        },
        'sub.action2':function(ctx){
          return 'world'
        }
    }
});

broker.call("math.sub.action1")
```
