### ISSUE TITLE
Services/actions goes offline and never come back

### ISSUE THREAD

**Issue by WoLfulus** [ice-services/moleculer#73]
I don't know if this is NATS specific and I couldn't figure out why this happens, but can be easily reproduced:

1. Start a service connected to a NATS endpoint
2. Connect a cli instance with `moleculer connect nats://localhost:4222`
3. Stop the service and start it again.
3. On the cli type `actions` and you'll see all actions offline.
4. Start a new cli instance the same way and execute `actions` too. All actions are online.
5. Old cli is still in "failed" mode.

https://files.gitter.im/ice-services/moleculer/Dna6/image.png

**Comment by icebob** [comment]
Fixed in v0.9.1
