### ISSUE TITLE
Built-in logger 'logger.debug' doesn't print anything in Node 8

### ISSUE THREAD

**Issue by tiaod** [ice-services/moleculer#88]
Before Node 8, `console.debug` is undefined.
```
Now using node v6.11.2 (npm v3.10.10)      
> console.debug('hello')                                     
TypeError: console.debug is not a function            
```
It will default to `baseLogger["info"]`
https://github.com/ice-services/moleculer/blob/943ce4724b054284c1051ebad7244e0755bd8759/src/logger.js#L87
However, in Node 8, `console.debug` is exposed and doesn't print anything.
```
Now using node v8.4.0 (npm v5.3.0)       
> console.debug                   
[Function: debug]                 
> console.debug('hello world')    
undefined                         
> 
```
So the `logger.debug` is not working anymore.

Maybe relate to: https://github.com/nodejs/node/issues/12675

**Comment by icebob** [comment]
Thank you!
