### ISSUE TITLE
Service metadata

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#91]
Add some metadata for services which is transferred with the `INFO` packet to all other nodes too. You can use it to store service specific information (like Docker labels).

Example:
```js
module.exports = {
	name: "posts",
	settings: { ... },
	metadata: {
		...,
		scalable: true,
		...etc
	},
	actions: { ... },
	events: { ... }
}
```

You can access this property with `$node.services` action or inside service with `this.metadata`.

Ping @WoLfulus

**Comment by WoLfulus** [comment]
Awesome!
This should be just a place to store any type of data and/or format, but we must guide people into some type of "best pratices", like namespacing the data in order to keep it usable by external/custom mixins and extensions later (avoid name clashing).

**Comment by icebob** [comment]
I started to implement it. @WoLfulus Do you have any idea for "best practices"?

**Comment by WoLfulus** [comment]
I haven't thought about it yet, but should be as the user wishes, to avoid enforcing anything. It could be open for discussion and a "try doing it like this" in the documentation later.
 
I haven't covered my cases just yet :(
