### ISSUE TITLE
Update AMQP for 0.11

### ISSUE THREAD

**Issue by icebob** [ice-services/moleculer#93]
We need to update the AMQP transporter to the new [v2 protocol](#86).

@Nathan-Schwartz I'm going to try it, but maybe I need your help as well :)

**Comment by icebob** [comment]
@Nathan-Schwartz If you have time, could you test & review my changes?
https://github.com/ice-services/moleculer/blob/next-events/src/transporters/amqp.js

I changed `EVENT` codes like `REQUEST`, but the difference is the event can be broadcast-et, and grouped.
I broadcasted (no `packet.payload.groups`˙) I send the packet on normal way. But if it has groups, I send to the grouped event queues, which is similar like `REQUEST`

Thanks in advance!

**Comment by Nathan-Schwartz** [comment]
@icebob Awesome! I think I can take a look a little later today 🙂

**Comment by icebob** [comment]
Thanks. I fixed & updated unit test, but integration test failed :(

**Comment by icebob** [comment]
I found some problem with balancing.... I'm working on it yet.

**Comment by icebob** [comment]
@Nathan-Schwartz there are some problem with the current implementation.

1. can't do direct call to a specified node.
2. circuit breaker is not working properly, because broker select "node-1", but rabbitmq maybe send the request to node-2 which return error. In this case broker open "node-1" circuit-breaker what is incorrect.

The first issue can be solved if we create REQ.<nodeID> queues as well like I do with events. And if it is a direct call we send to the node queue instead of action queue, right?
*But it can conflict with action named queues. If the action name is `a.b`˙and nodeID is `a.b` both name will be `MOL.REQ.a.b`*

The second issue can be solved (perhaps) if the circuit breaker take out nodeID from the Error instead of the source Context.

What do you think?

Btw, I added AMQP transporter to the benchmark and the result is very strange.
```js
Platform info:
==============
   Windows_NT 6.1.7601 x64
   Node.JS: 6.10.2
   V8: 5.1.281.98
   Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz × 4

Suite: Transport with 10bytes
√ Fake*            25,008 rps
√ NATS*             3,900 rps
√ Redis*            4,598 rps
√ MQTT*             4,337 rps
√ AMQP*                23 rps
```
Do you have any idea why it is so slow?

**Comment by Nathan-Schwartz** [comment]
@icebob I am not sure why it was slow in the benchmark. Last week I think I was able to do ~10,000 rps (perhaps 5k round trip?) with the AMQP transporter (v0.10). I'll test again to see what I get.

Why is it necessary to do a request to a specific node? If all nodes are of the same service, it seems like they should all behave the same.

To avoid naming conflicts in the solution you suggested, we could prefix the queues:
`MOL.REQ.action-<nodeID>`
`MOL.REQ.nodeID-<nodeID>`

I don't know very much about the circuit breakers, I'll have to read more about it.

**Comment by icebob** [comment]
You should use direct call if you want to get health info from a specified node `$node.health`. 
The 10k rps with Moleculer?

**Comment by Nathan-Schwartz** [comment]
I see, thanks!

I'll run the test again locally and see what I get.

**Comment by Nathan-Schwartz** [comment]
I ran it again and it is completing 1540 requests per second (request + response time). Still slow, but faster than 23 🙂

**Comment by icebob** [comment]
Thank you. It's better. I will test it again.

**Comment by icebob** [comment]
If you checkout next-events branch you can run the benchmark with the `npm run bench transporters` command.

**Comment by icebob** [comment]
I improved the AMQP transporter & transit, broker, registry codes. There is a new broker option as `disableBalancer`. With it you can disable the Moleculer built-in balancer. Currently it can work only with AMQP transporter. 
If you use the built-in balancer, every message is transferred to the targetted node like in other transporters. It doesn't use the RabbitMQ balancer, put messages to the node queues.
If you disable it, every call & emit will be transferred via transporter (locals too) and use the RabbitMQ balancer, put messages to the action & event queues. 
> In this case the Moleculer built-in circuit-breaker is not available.

I will try to make a figure about flow. @Nathan-Schwartz Could you share your draw.io project with me, what you used in #72?

**Comment by Nathan-Schwartz** [comment]
@icebob Awesome! I'll take a look at your branch. Yeah, I can share the draw.io project :+1:

**Comment by Nathan-Schwartz** [comment]
@icebob Branch looks great! Here is a link, sorry for the wait: https://drive.google.com/file/d/0B2CLtHU8jVlicVV3VDdGeHF1OGs/view?usp=sharing

**Comment by icebob** [comment]
Thanks!
