### ISSUE TITLE
Inconsistent lifecycle callbacks

### ISSUE THREAD

**Issue by WoLfulus** [ice-services/moleculer#97]
I found out that lifecycle callbacks are a little counterintuitive. Can we review how these works?

For example, I was expecting both cases to work "exactly" the same (both callbacks fired), but the second one doesn't fire at all - dispatches are literally done inside broker.call()

Its counterintuitive because in both cases the service is "started".

```javascript
broker = new ServiceBroker({
	logger: console,
	logLevel: "debug",
});

broker.createService({
	name: "test",
	created() {
		this.logger.debug("created called");
	},
	started() {
		this.logger.debug("started called");
	}
});

await broker.start();
```

```
created called
started called
```

and 

```javascript
broker = new ServiceBroker({
	logger: console,
	logLevel: "debug",
});

await broker.start();

broker.createService({
	name: "test",
	created() {
		this.logger.debug("created called");
	},
	started() {
		this.logger.debug("started called");
	}
});
```

```
created called
```

also, by "started" I expect to be able to call the network already if there's a transport involved. If this doesn't make sense, maybe we can add a new "ready" event to cover this?

**Comment by icebob** [comment]
Thank you @WoLfulus. I was a bug, but I fixed.

**Comment by WoLfulus** [comment]
Thank you!
