### ISSUE TITLE
Redis Cacher: Parse-Error when retrieving String values from Redis

### ISSUE THREAD

**Issue by Birkenstab** [ice-services/moleculer#98]
The following error Redis Cacher is thrown when the Redis Cacher tries to retrieve a cached String value from Redis:
```
Redis result parse error. SyntaxError: Unexpected token F in JSON at position 0
    at JSON.parse (<anonymous>)
    at client.get.then (/Users/moritz/Documents/Moleculer-Versuche/RedisCacher-Bug/node_modules/moleculer/src/cachers/redis.js:99:18)
```

Redis Cacher stores non-object values not as JSON [redis.js:118](https://github.com/ice-services/moleculer/blob/1e109b9af6b3c71a5b4897fe3e3e0abfd10d84db/src/cachers/redis.js#L118) so the String "Foo Bar" is stored in Redis without double quotes. When reading this value from Redis it gets parsed as JSON which results in the error above because its invalid JSON.

This can be fixed by always using JSON.stringify on every datatype but maybe at the cost of performance?

I think storing different datatypes should be added to the test.
Should I create a Pull request?

Code to reproduce
```JavaScript
const { ServiceBroker } = require("moleculer");
let broker = new ServiceBroker({
  cacher: "redis",
  logger: true
});

broker.createService({
    name: "strings",
    actions: {
        concat: {
            cache: true,
            handler(ctx) {
                return `${ctx.params.a} ${ctx.params.b}`;
            }
        }
    }
});
broker.start()
    .then(() => broker.call("strings.concat", { a: "Foo", b: "Bar" }))
    .then((res => console.log("Result (not from cache): " + res)))
    .then(() => broker.call("strings.concat", { a: "Foo", b: "Bar"}))
    .then((res => console.log("Result (should be from cache): " + res)))
    .catch(err => console.error(`Error occured! ${err.message}`));
```

**Comment by icebob** [comment]
Ohh, nice bug. Just need to remove [this condition](https://github.com/ice-services/moleculer/blob/master/src/cachers/redis.js#L118) & verify tests.
Could you make a PR with the fix?
